import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import {
  MicrophoneIcon, ViewGridIcon
} from '@heroicons/react/solid';
import {  SearchIcon } from '@heroicons/react/outline';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className='flex w-full p-5 justify-between text-sm text-gray-700'> 
        {/* Left header */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>

        {/* Right header */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>

          {/* Icon */}
          <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer'/>
          
          <Avatar url='https://coaching.papareact.com/ai9'/>
        </div>
      </header>

      {/* Body */}
      <form>
        <Image src='https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png' width={300} height={100}/>
      </form>
      <div>
        <SearchIcon/>
      </div>

      {/* Footer */}
              
    </div>
  )
}
